version: "3.9"

services:
  web:
    build: ./frontend
    ports:
      - "8082:80"
    networks:
      - frontend

  api:
    build: ./backend
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - backend

networks:
  frontend:
  backend:
